### ISSUE TITLE
App Installs TODO

### ISSUE THREAD

**Issue by Morpheus636** [Morpheus636/desktop-config#3]
# Remove Snap!
https://onlinux.systems/guides/20220524_how-to-disable-and-remove-snap-on-ubuntu-2204

# Installers
### Custom Installers
- [x] Drive-Sync
- [x] Discord
- [x] Docker
- [ ] Pop-Shell
- [ ] Pyenv + Poetry (Not Urgent)
- [ ] Zeal-CLI (Not Urgent)
- [x] Pycharm

### Apt w/ Additional Repo
- [x] VsCode (Apt Repo)
- [x] Chrome (Apt Repo)

### Apt w/ Default Repos
- [x] git
- [x] git-lfs
- [x] curl
- [x] software-properties-common
- [x] apt-transport-https
- [x] wget
- [x] libcanberra-gtk-module
- [x] default-jdk
- [x] gnome-tweaks
- [x] gnome-shell-extensions
- [x] vim
- [x] zeal
- [x] filezilla
- [x] build-essential
- [x] transmission-gtk
- [x] tree
- [x] hexchat
- [x] gimp
- [x] rawtherapee
- [x] libreoffice
- [x] virtualbox
- [x] gcc
- [x] g++
- [x] make
- [x] node-typescript
- [x] thunderbird

### Flatpak
- [x] add flathub repo
- [x] app.bluebubbles.BlueBubbles
- [x] org.eclipse.Java
