### ISSUE TITLE
Config TODO

### ISSUE THREAD

**Issue by Morpheus636** [Morpheus636/desktop-config#4]
- [ ] Create /home/user/src directory
- [ ] Set Wallpaper
- [ ] Set Profile Picture
- [ ] SSH
- [ ] Git Config
- [ ] BASH Config
- [ ] Gnome/Gnome Tweaks Config
- [ ] Zeal Docset Installation
- [ ] Install Theme and Icons (`/usr/share/themes` and `/usr/share/icons`)

## Private
- [ ] VPN Config
- [ ] Thunderbird Config
- [ ] BlueBubbles Config
